language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

#env:
#    - PLATFORMIO_CI_SRC=src/Goggles.ino src/gamma.h

install:
    - pip install -U platformio
    - wget https://github.com/adafruit/Adafruit_NeoPixel/archive/master.zip -O /tmp/adafruit_neopixel.zip
    - unzip /tmp/adafruit_neopixel.zip -d /tmp

script:
    - platformio ci --lib=/tmp/Adafruit_NeoPixel-master --project-conf platformio.ini src/Goggles.ino src/gamma.h
