language: python
python:
  - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - wget https://github.com/adafruit/Adafruit_NeoPixel/archive/master.zip -O /tmp/adafruit_neopixel.zip
  - unzip /tmp/adafruit_neopixel.zip -d /tmp

script:
  - platformio ci --lib=/tmp/Adafruit_NeoPixel-master --project-conf platformio.ini src/main.cpp lib/Goggles/Goggles.h lib/Goggles/Goggles.cpp
